[package]
name = "async_msp_cli"
version = "0.1.3"
authors = ["Ilya Guterman <amfernusus@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Async msp cli for iNav and BetaFlight"
repository = "https://github.com/amfern/inav_msp_cli.rs"
readme = "README.md"
categories = ["asynchronous", "embedded", "command-line-utilities"]
keywords = ["msp", "multiwii", "inav", "betaflight"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiwii_serial_protocol_v2 = "0.1.6"
async_msp_lib = "0.1.4"
serialport = "3.3.0"
packed_struct = "0.3"
packed_struct_codegen = "0.3"
futures = "0.3.4"
clap-v3 = "~3.0.0-beta.1"
itertools = "0.9.0"

[dependencies.async-std]
version = "1.5.0"
features = ["unstable", "attributes"]